// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaYgPauieMromJfb27U6j5-OU_VTWTYDQ',
    appId: '1:245401359956:web:6a4530b6c7ef133288ffc1',
    messagingSenderId: '245401359956',
    projectId: 'psjoanna-e55aa',
    authDomain: 'psjoanna-e55aa.firebaseapp.com',
    storageBucket: 'psjoanna-e55aa.firebasestorage.app',
    measurementId: 'G-SXCGPFJECN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOhpOsNu7in4TFIYh9J8ppPz8GbACGboY',
    appId: '1:245401359956:android:aba1187e2b0177d888ffc1',
    messagingSenderId: '245401359956',
    projectId: 'psjoanna-e55aa',
    storageBucket: 'psjoanna-e55aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfPhTTAmBdq4jC67iL79-jbLHZF6UaAQY',
    appId: '1:245401359956:ios:67632fda181b5b3f88ffc1',
    messagingSenderId: '245401359956',
    projectId: 'psjoanna-e55aa',
    storageBucket: 'psjoanna-e55aa.firebasestorage.app',
    iosClientId: '245401359956-psa5urv41jb4sb5oq56fc8bv4q5re1l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikacja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfPhTTAmBdq4jC67iL79-jbLHZF6UaAQY',
    appId: '1:245401359956:ios:67632fda181b5b3f88ffc1',
    messagingSenderId: '245401359956',
    projectId: 'psjoanna-e55aa',
    storageBucket: 'psjoanna-e55aa.firebasestorage.app',
    iosClientId: '245401359956-psa5urv41jb4sb5oq56fc8bv4q5re1l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikacja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaYgPauieMromJfb27U6j5-OU_VTWTYDQ',
    appId: '1:245401359956:web:c42a4e75cf3a381e88ffc1',
    messagingSenderId: '245401359956',
    projectId: 'psjoanna-e55aa',
    authDomain: 'psjoanna-e55aa.firebaseapp.com',
    storageBucket: 'psjoanna-e55aa.firebasestorage.app',
    measurementId: 'G-ZQQYVRJ30D',
  );
}
